# Generated by Django 3.1.1 on 2020-09-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='website',
            new_name='linkenin',
        ),
    ]
