# Generated by Django 3.1.1 on 2020-09-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.blogpost'),
        ),
    ]
