# Generated by Django 3.1.1 on 2020-09-02 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('postdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('offer_nature', models.CharField(blank=True, max_length=100)),
                ('Vacancy', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/$D/')),
            ],
        ),
        migrations.CreateModel(
            name='Offerdemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('cv', models.FileField(blank=True, null=True, upload_to='CV/%Y/%m/$D/')),
                ('letter', models.TextField(blank=True)),
                ('application_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offers.offer')),
            ],
        ),
    ]
