# Generated by Django 3.1.1 on 2020-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='offerdemand',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='CV/%Y/%m/%d/'),
        ),
    ]
