# Generated by Django 3.1.1 on 2020-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200902_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdemand',
            name='letter',
        ),
        migrations.AddField(
            model_name='offerdemand',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
