# Generated by Django 3.1.1 on 2020-09-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20200909_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offerdemand',
            new_name='Application',
        ),
    ]
