# Generated by Django 3.1.1 on 2020-09-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20200910_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='offer',
            new_name='offer_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='offerId',
        ),
    ]
