# Generated by Django 3.1.1 on 2020-09-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20200911_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='offer_id',
            new_name='offer',
        ),
    ]
