# Generated by Django 3.1.1 on 2020-09-17 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20200914_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
